controllers:
    resource: ../src/Controller/
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::index

task_create:
    path: /task/create
    controller: App\Controller\TaskController::create

task_create_new:
    path: /task/create/new
    controller: App\Controller\TaskController::createTask

task_view:
    path: /task/{id}
    controller: App\Controller\TaskController::view

task_edit:
    path: /task/edit/{id}
    controller: App\Controller\TaskController::edit

task_update:
    path: /task/update/{id}
    controller: App\Controller\TaskController::update

task_delete:
    path: /task/delete/{id}
    controller: App\Controller\TaskController::delete